[0m12:47:14.832256 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002886051EF90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002885E3D8B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002886165C190>]}


============================== 12:47:14.852362 | 19d86da7-5a13-43ab-a577-e9f86c823dbf ==============================
[0m12:47:14.852362 [info ] [MainThread]: Running with dbt=1.10.2
[0m12:47:14.852845 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Tarik\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt init dbt_tpch_project', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:47:14.871256 [info ] [MainThread]: Creating dbt configuration folder at C:\Users\Tarik\.dbt
[0m12:47:14.872981 [debug] [MainThread]: Starter project path: C:\Users\Tarik\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\include\starter_project
[0m12:47:14.890582 [info ] [MainThread]: 
Your new dbt project "dbt_tpch_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:47:14.890977 [info ] [MainThread]: Setting up your profile.
[0m12:47:14.891973 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m12:47:14.892850 [debug] [MainThread]: Command `dbt init` failed at 12:47:14.892745 after 0.19 seconds
[0m12:47:14.893149 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028861626C40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000288627BF0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000288627AC490>]}
[0m12:47:14.893465 [debug] [MainThread]: Flushing usage events
[0m12:47:15.075761 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:06:09.841673 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178C7B46510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178C59A0910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178C8CAFD90>]}


============================== 13:06:09.846046 | f9b07b57-6b21-444e-9e80-59bdca43ee43 ==============================
[0m13:06:09.846046 [info ] [MainThread]: Running with dbt=1.10.2
[0m13:06:09.846562 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Tarik\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt init dbt_tpch_project', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:06:09.866865 [info ] [MainThread]: A project called dbt_tpch_project already exists here.
[0m13:06:09.867792 [debug] [MainThread]: Command `dbt init` succeeded at 13:06:09.867674 after 0.12 seconds
[0m13:06:09.868078 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178C8CF5E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178C8D6A210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000178C8B27240>]}
[0m13:06:09.868383 [debug] [MainThread]: Flushing usage events
[0m13:06:09.938158 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:28:24.639567 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A17FD16510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A17DB80910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A101EF7D90>]}


============================== 13:28:24.643578 | 5efd14ac-67cb-447b-ab1b-ef28e335858e ==============================
[0m13:28:24.643578 [info ] [MainThread]: Running with dbt=1.10.2
[0m13:28:24.644064 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Tarik\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run --select raw.*', 'send_anonymous_usage_stats': 'True'}
[0m13:28:24.644447 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Tarik\dbt_tpch\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:28:24.645324 [debug] [MainThread]: Command `dbt run` failed at 13:28:24.645220 after 0.13 seconds
[0m13:28:24.645621 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A101F2CB00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A100E22210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002A100D878A0>]}
[0m13:28:24.645920 [debug] [MainThread]: Flushing usage events
[0m13:28:24.850614 [debug] [MainThread]: An error was encountered while trying to flush usage events
